server:
  port: 1112
eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
#    prefer-ip-address: true
#    ip-address: 192.168.2.56
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone:  http://127.0.0.1:1112/eureka/
  server:
    enable-self-preservation: false
security:
  basic:
    enabled: false
spring:
  application:
    name: registy
#  user:
#    name: user
#    password: 123123