spring:
      application:
                  name: compute-service

server:
      port: 2221

eureka:
      client:
            serviceUrl:
                      defaultZone:  http://127.0.0.1:1111/eureka/