server:
        port: 1111

eureka:
      instance:
              lease-renewal-interval-in-seconds: 3
      client:
            register-with-eureka: false
            fetch-registry: false
            serviceUrl:
                      defaultZone:  http://127.0.0.1:${server.port}/eureka/