spring:
      application:
                  name: ribbon-consumer

server:
      port: 4444

eureka:
      client:
            serviceUrl:
                      defaultZone:  http://127.0.0.1:1111/eureka/