spring:
  application:
    name: HYSRTIX
server:
  port: 5555

eureka:
  client:
    serviceUrl:
      defaultZone:  http://user:123123@localhost:1111/eureka/
#    register-with-eureka: false
endpoints:
  actuator:
    enabled: true
hystrix:
  metrics:
    enabled: true