server:
        port: 4444
spring:
      application:
                name: feign-consumer
eureka:
      client:
            serviceUrl:
                      defaultZone:  http://127.0.0.1:1111/eureka/