spring:
  application:
    name: user-service
server:
  port: 2223
eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  http://127.0.0.1:1111/eureka/