spring:
  application:
    name: user-service
server:
  port: 2223
eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  http://docker:1112/eureka/